### PR TITLE
Rewrote the HexToHSB function. This fixes #141

### LINKED ISSUE #141: Does the color '#c411a6' break randomColor?
I'm seeing that this code breaks the generation or `randomColor`, but I find this esoterical so it's likely something else

```js
  console.log(randomColor({
    count: 5,
    luminosity: 'light',
    hue: '#c411a6',
  }))
```

I do see it in a codesandbox

```js
import "./styles.css";
import randomColor from 'randomcolor'

console.log(randomColor({
  count: 5,
  luminosity: 'light',
  hue: '#ffffff',
}))

console.log(randomColor({
  count: 5,
  luminosity: 'light',
  hue: '#c411a6',
}))

document.getElementById("app").innerHTML = `
<h1>Hello Vanilla!</h1>
<div>
  We use the same configuration as Parcel to bundle this sandbox, you can find more
  info about Parcel 
  <a href="https://parceljs.org" target="_blank" rel="noopener noreferrer">here</a>.
</div>
`;
```

The hue value is from a previous randomly `randomColor`-generated array

image

### PR DESCRIPTION
**Pull request by naveloranges**
The bug was originated from the current HexToHSB function returning `undefined` when passed particular hex values as argument.

### CODE REVIEW

**Comment by davidmerfield** [comment]
Hello! Thanks for this. I will merge if you remove the linting/white-space changes, and the changes to `.gitignore`. 

Sincerely, David

**Comment by itsmygit** [comment]
Thanks for the feedback. I did it. Now it's ready to be merged.

**Comment by davidmerfield** [comment]
Thanks for making those changes – now I'm worried that unfortunately that function doesn't do what is says it does. HSB seems to be different to HSL and the function you include seems to deal with HSL rather than HSB.

I will look into this further

**Comment by itsmygit** [comment]
Okay. Glad if that helped.

**Pull request merged**
