### PR TITLE
Maximise color difference

### PR DESCRIPTION
**Pull request by m-bourkha**
- I changed the randomWithin method to generate hues that are evenly distributed.
- I added the method getRealHueRange that return the range where a given hue fits in.
- I changed the pickHue method that return hue within a range that is not already taken.

### CODE REVIEW

**Comment by logolab** [comment]
Is this merged into the master already?

**Comment by davidak** [comment]
@davidmerfield could you review and hopefully merge this?

I want to use this library for graphs but the colors look too similar!

```
var colors = randomColor({
  count: number_of_queries,
  luminosity: 'dark',
  seed: 'Aegi1V'
  });
```



screenshot from 2018-11-12 20-58-06

**Comment by davidmerfield** [comment]
Great stuff! Thank you for putting this together

**Comment by davidak** [comment]
Does this actually solve the problem for you?

From 7 random colors are 2-3 still identical.

Screenshot from 2019-04-10 15-16-33

(without seed)

**Comment by DamienCassou** [comment]
I confirm that I get very similar colors too:
testimage

**Pull request merged**
