### PR TITLE
Output UMD and ES module builds using rollup

### PR DESCRIPTION
**Pull request by keithamus**
This introduces [rollup](https://rollupjs.org/) as a dev-dependency which allows us to author the original file using ES6 import/export syntax, which Rollup can read and subsequently output as a UMD file.  The file with ES6 import syntax can subsequently be consumed by bundler tools like Rollup and WebPack to create more compact files within those tools.

This should change nothing for users who already consume the UMD version - but it should improve the code output for those that use tools such as Webpack and Rollup.

[Diff with whitespace removed](https://github.com/davidmerfield/randomColor/pull/111/files?utf8=%E2%9C%93&diff=unified&w=1#diff-aedc450f05d7fdbece420658c391133f)

### CODE REVIEW

**Comment by keithamus** [comment]
@davidmerfield how do you feel about this one? It adds a devdependency in rollup - but the benefit is that files can be consumed by modern build tools with less hassle.

**Comment by keithamus** [comment]
@davidmerfield any update on this? I'd love to see this get merged!

**Comment by Dig-Doug** [comment]
Hey @davidmerfield, any updates on this PR? I'd also like to see this change.

It looks a bit outdated now, but I'd be happy to update the PR if @keithamus doesn't have bandwidth.

**Comment by davidmerfield** [comment]
Hello Keith and Doug, sorry for taking so long to get this – I'm going to say no to this change – I don't want to introduce the dependency (the script is entirely dependency free at this point)

If we can adjust the script itself such that these modern tools can consume it – great, would be more than willing to merge

**Comment by keithamus** [comment]
@davidmerfield would you consider a branch which ships this only as an ES2016+ module, dropping the UMD script entirely?

**Comment by laike9m** [comment]
Has this change been released yet?

**Pull request closed without merging**
