### PR TITLE
Change seeds so they work the first time they are passed in

### PR DESCRIPTION
**Pull request by daviesgeek**
### Bug Report

Currently the way randomColor works, a seed will work the very first time it's passed in, but if the seed changes, it uses the last seed that was passed in to generate the color(s), and *then* it sets the new seed, causing the wrong output.

Here's an example:

```js
randomColor({seed: 1, count: 10})
// Output:
['#8bd343', '#a31f44', '#f23aa5', '#25bfd1', '#b9dd5d', '#b2ffd3', '#017984', '#c4214f', '#fcd928', '#55dbd2']


randomColor({seed: 2, count: 10}) // Note the seed has changed from 1 to 2
// Notice that this is the same array as when it was seeded with "1"
['#8bd343', '#a31f44', '#f23aa5', '#25bfd1', '#b9dd5d', '#b2ffd3', '#017984', '#c4214f', '#fcd928', '#55dbd2']

randomColor({seed: 2, count: 10}) // Note the seed is still 2
// This is now the correct array of colors
['#7ed65e', '#d8d82f', '#46e2a1', '#77eaea', '#d062fc', '#8e6af2', '#604ce0', '#e5d177', '#9df2e2', '#efcb8d']
```

As you can see, when you run the generator with one seed (first run), change the seed, run it again (second run), it generates the wrong array of colors. Then when you run it for the third time (with the 
same seed as the second run), it generates the correct array of colors.

### Solution

This pull request modifies the behavior of the seed option so that the seed is reset at the end of each run.

I've also written a test that fails if you use the original version of randomColor (before my changes), so that you can run it (via `npm run test`) and easily see the bug.

#### Misc

I've also bumped the version number in package.json, as well as added a version number to the bower.json file. I also created a new tag for the 0.4.1 release (not sure if this will move over when my PR is merged in though…)

### CODE REVIEW

**Comment by davidmerfield** [comment]
Hi Matthew! Thank you for your work in fixing this bug. I'd be happy to merge this if you remove the tests & associated metadata files from this pull request.

**Comment by kimmobrunfeldt** [comment]
@davidmerfield why do you not want tests for the project?

**Comment by daviesgeek** [comment]
Whoops! So sorry! Somehow I missed your comment. 

I am also wondering why you would not want tests for the project. Do you mind explaining why?

**Comment by davidmerfield** [comment]
@kimmobrunfeldt @daviesgeek It's not that I don't want to use tests – I don't want to use Karma/Jasmine. I'd rather move the question of how to add tests to this project to a separate issue/pull request. It is much easier to manage single-problem pull requests. Again, thank you for your work fixing this bug and apologies for my delayed response!

**Comment by daviesgeek** [comment]
Okay I've update the PR to remove the unit tests!

**Comment by davidmerfield** [comment]
Perfect, thank you again!

**Pull request merged**
