### PR TITLE
Suggested PR which will allow users to specify independent ranges for H, S and L levels.

### PR DESCRIPTION
**Pull request by Xliff**
Addresses davidmerfield/randomColor#103.

### CODE REVIEW

**Comment by davidmerfield** [comment]
Hello! Thanks for this, I like it. I also want to propose a few changes, and I'm happy to discuss and or implement them:

- rename options.hueRange to options.hue
   hue can now be a color string, a fixed integer, or an integer tuple:
   {hue: 'orange'} 
   {hue: 123}
   {hue: [123, 300]}
- rename options.brightnessRange to options.brightness
- rename options.saturationRange to options.saturation
- deprecate options.luminosity, use options.brightness going forward

**Comment by Xliff** [comment]
I'd be happy to, in my Copious Amounts of Free Time™ :)

**Comment by davidmerfield** [comment]
Ha! I wasn't asking you to do this – I wanted to get your feedback on these changes in case you had any thoughts before I went ahead and implemented them

**Comment by Xliff** [comment]
Nope! I think your additions to it are a great idea.

**Pull request closed without merging**
