### PR TITLE
Added seeded RNG. New option parameter seed and a number. No checks f…

### PR DESCRIPTION
**Pull request by koide**
…or seed validity are made. 

Usage sample: 
randomColor({seed: 42})

### CODE REVIEW

**Comment by klaemo** [comment]
Is there any work left to be done on this PR? I'd love to see this merged as it would be very useful for me.

**Comment by koide** [comment]
David said he was going on a long trip and he would review when back. I'm waiting for his comments to modify what's needed to get this merged.

**Comment by davidmerfield** [comment]
Terribly sorry about the delay – just reviewed the code and it looks great. Thanks for this @koide

**Comment by klaemo** [comment]
Thank you @davidmerfield and @koide :)

**Pull request merged**
